import styles from "../../Styles/modules/privacy_terms/index.module.scss"

const termsContent = [
  `Introduction`,
  `Welcome to the DGP Capital Management Limited's privacy policy.`,
  `DGP Capital Management Limited respects your privacy and is committed to protecting your personal data. This privacy policy will inform you as to how we look after your personal data when you visit our website (regardless of where you visit it from) and tell you about your privacy rights and how the law protects you.`,
  `Please also use the Glossary to understand the meaning of some of the terms used in this privacy policy.`,
  `1. IMPORTANT INFORMATION AND WHO WE ARE`,
  `2. THE DATA WE COLLECT ABOUT YOU`,
  `3. HOW IS YOUR PERSONAL DATA COLLECTED?`,
  `4. HOW WE USE YOUR PERSONAL DATA`,
  `5. DISCLOSURES OF YOUR PERSONAL DATA`,
  `6. INTERNATIONAL TRANSFERS`,
  `7. DATA SECURITY`,
  `8. DATA RETENTION`,
  `9. YOUR LEGAL RIGHTS `,
  `10. GLOSSARY`,
  `10. GLOSSARY`,
  `10. GLOSSARY`,
  `1. Important information and who we are`,
  `Purpose of this privacy policy`,
  `This privacy policy aims to give you information on how DGP Capital Management Limited collects and processes your personal data through your use of this website.`,
  `This website is not intended for children and we do not knowingly collect data relating to children.`,
  `It is important that you read this privacy policy together with any other privacy policy or fair processing policy we may provide on specific occasions when we are collecting or processing personal data about you so that you are fully aware of how and why we are using your data. This privacy policy supplements other notices and privacy policies and is not intended to override them.`,
  `Controller`,
  `DGP Capital Management Limited is the controller and responsible for your personal data (collectively referred to as “DGP”, "we", "us" or "our" in this privacy policy).`,
  `DGP Capital Management Limited is the controller and responsible for this website.`,
  `We have appointed a data privacy manager who is responsible for overseeing questions in relation to this privacy policy. If you have any questions about this privacy policy, including any requests to exercise your legal rights, please contact the data privacy manager using the details set out below.`,
  `Contact details`,
  `If you have any questions about this privacy policy or our privacy practices, please contact our data privacy manager in the following ways:`,
  `Full name of legal entity: DGP Capital Management Limited`,
  `Email address: admin@digitalgravity.com`,
  `Postal address: 15 Stratton Street, London, W1J 8LQ`,
  `You have the right to make a complaint at any time to the Information Commissioner's Office (ICO), the UK regulator for data protection issues (www.ico.org.uk). We would, however, appreciate the chance to deal with your concerns before you approach the ICO so please contact us in the first instance.`,
  `Changes to the privacy policy and your duty to inform us of changes`,
  `We keep our privacy policy under regular review. This version was last updated on 24th of July 2023.`,
  `It is important that the personal data we hold about you is accurate and current.`,
  `Third-party links`,
  `This website may include links to third-party websites, plug-ins and applications. Clicking on those links or enabling those connections may allow third parties to collect or share data about you. We do not control these third-party websites and are not responsible for their privacy statements. When you leave our website, we encourage you to read the privacy policy of every website you visit.`,
  `2. The data we collect about you`,
  `Personal data, or personal information, means any information about an individual from which that person can be identified. It does not include data where the identity has been removed (anonymous data).`,
  `We may collect, use, store and transfer different kinds of personal data about you which we have grouped together as follows:`,
  `· Technical Data includes internet protocol (IP) address, your login data, browser type and version, time zone setting and location, browser plug-in types and versions, operating system and platform, and other technology on the devices you use to access this website.`,
  `· Usage Data includes information about how you use our website. `,
  `We also collect, use and share Aggregated Data such as statistical or demographic data for any purpose. Aggregated Data could be derived from your personal data but is not considered personal data in law as this data will not directly or indirectly reveal your identity. For example, we may aggregate your Usage Data to calculate the percentage of users accessing a specific website feature. However, if we combine or connect Aggregated Data with your personal data so that it can directly or indirectly identify you, we treat the combined data as personal data which will be used in accordance with this privacy policy.`,
  `We do not collect any Special Categories of Personal Data about you (this includes details about your race or ethnicity, religious or philosophical beliefs, sex life, sexual orientation, political opinions, trade union membership, information about your health, and genetic and biometric data). Nor do we collect any information about criminal convictions and offences.`,
  `3. How is your personal data collected?`,
  `We use different methods to collect data from and about you including through:`,
  `· Direct interactions. You may give us your Identity and Contact by filling in forms or by corresponding with us by post, phone, email or otherwise. This includes personal data you provide when you:`,
  `· give us feedback or contact us.`,
  `· Automated technologies or interactions. As you interact with our website, we will automatically collect Technical Data about your equipment, browsing actions and patterns. We collect this personal data by using cookies, server logs and other similar technologies. We may also receive Technical Data about you if you visit other websites employing our cookies. Please see our cookie policy [LINK] for further details.`,
  `· Third parties or publicly available sources. We will receive personal data about you from various third parties and public sources as set out below:`,
  `· Technical Data from the following parties:`,
  `· Identity and Contact Data from introductory agents based inside the UK .`,
  `· Identity and Contact Data from publicly available sources such as Companies House based inside the UK.`,
  `4. How we use your personal data`,
  `· Where we need to perform the contract we are about to enter into or have entered into with you.`,
  `· Where it is necessary for our legitimate interests (or those of a third party) and your interests and fundamental rights do not override those interests.`,
  `· Where we need to comply with a legal obligation.`,
  `See GLOSSARY, LAWFUL BASIS to find out more about the types of lawful basis that we will rely on to process your personal data.`,
  `Generally, we do not rely on consent as a legal basis for processing your personal data.`,
  `Purposes for which we will use your personal data:`,
  `We have set out below a description of all the ways we plan to use your personal data, and which of the legal bases we rely on to do so. We have also identified what our legitimate interests are where appropriate.`,
  `Note that we may process your personal data for more than one lawful ground depending on the specific purpose for which we are using your data. Please contact us if you need details about the specific legal ground we are relying on to process your personal data where more than one ground has been set out in the table below.`,
  `Purpose/Activity`,
  `Type of data`,
  `Lawful basis for processing including basis of legitimate interest`,
  `Performance of a contract with you`,
  `To manage our relationship with you which will include:`,
  `(a) Notifying you about changes to our terms or privacy policy`,
  `(b) Asking you to leave a review or take a survey`,
  `(c) Identity`,
  `(d) Contact`,
  `(e) Profile`,
  `(f) Marketing and Communications`,
  `(g) Performance of a contract with you`,
  `(h) Necessary to comply with a legal obligation`,
  `(i) Necessary for our legitimate interests (to keep our records updated and to study how customers use our products/services)`,
  `To administer and protect our business and this website (including troubleshooting, data analysis, testing, system maintenance,  support, reporting and hosting of data) `,
  `(a) Identity`,
  `(b) Contact`,
  `(c) Technical`,
  `(d) Necessary for our legitimate interests (for running our business, provision of administration and IT services, network security, to prevent fraud and in the context of a business reorganisation or group restructuring exercise)`,
  `(e) Necessary to comply with a legal obligation`,
  `To deliver relevant website content to you.`,
  `(a) Identity`,
  `(b) Contact`,
  `(c) Profile`,
  `(d) Usage`,
  `(e) Marketing and Communications`,
  `(f) Technical`,
  `To use data analytics to improve our website, client relationships and experiences`,
  `(a) Technical `,
  `(b) Usage`,
  `Cookies`,
  `You can set your browser to refuse all or some browser cookies, or to alert you when websites set or access cookies. If you disable or refuse cookies, please note that some parts of this website may become inaccessible or not function properly. For more information about the cookies we use, please see our  COOKIE POLICY.`,
  `Change of purpose`,
  `We will only use your personal data for the purposes for which we collected it, unless we reasonably consider that we need to use it for another reason and that reason is compatible with the original purpose. If you wish to get an explanation as to how the processing for the new purpose is compatible with the original purpose, please contact us.`,
  `If we need to use your personal data for an unrelated purpose, we will notify you and we will explain the legal basis which allows us to do so.`,
  `Please note that we may process your personal data without your knowledge or consent, in compliance with the above rules, where this is required or permitted by law.`,
  `5. International transfers`,
  `We do not transfer your personal data outside the UK.`,
  `6. Data security`,
  `We have put in place appropriate security measures to prevent your personal data from being accidentally lost, used or accessed in an unauthorised way, altered or disclosed. In addition, we limit access to your personal data to those employees, agents, contractors and other third parties who have a business need to know. They will only process your personal data on our instructions and they are subject to a duty of confidentiality.`,
  `We have put in place procedures to deal with any suspected personal data breach and will notify you and any applicable regulator of a breach where we are legally required to do so.`,
  `7. Data retention`,
  `How long will you use my personal data for?`,
  `We will only retain your personal data for as long as reasonably necessary to fulfil the purposes we collected it for, including for the purposes of satisfying any legal, regulatory, tax, accounting or reporting requirements. We may retain your personal data for a longer period in the event of a complaint or if we reasonably believe there is a prospect of litigation in respect to our relationship with you.`,
  `To determine the appropriate retention period for personal data, we consider the amount, nature and sensitivity of the personal data, the potential risk of harm from unauthorised use or disclosure of your personal data, the purposes for which we process your personal data and whether we can achieve those purposes through other means, and the applicable legal, regulatory, tax, accounting or other requirements.`,
  `In some circumstances you can ask us to delete your data: see below for further information.`,
  `In some circumstances we will anonymise your personal data (so that it can no longer be associated with you) for research or statistical purposes, in which case we may use this information indefinitely without further notice to you.`,
  `8. Your legal rights`,
  `Under certain circumstances, you have rights under data protection laws in relation to your personal data.  If you wish to exercise any data protection law rights please contact us.`,
  `You will not have to pay a fee to access your personal data (or to exercise any of the other rights). However, we may charge a reasonable fee if your request is clearly unfounded, repetitive or excessive. Alternatively, we could refuse to comply with your request in these circumstances.`,
  `What we may need from you`,
  `We may need to request specific information from you to help us confirm your identity and ensure your right to access your personal data (or to exercise any of your other rights). This is a security measure to ensure that personal data is not disclosed to any person who has no right to receive it. We may also contact you to ask you for further information in relation to your request to speed up our response.`,
  `Time limit to respond`,
  `We try to respond to all legitimate requests within one month. Occasionally it could take us longer than a month if your request is particularly complex or you have made a number of requests. In this case, we will notify you and keep you updated.`,
  `9. Glossary`,
  `LAWFUL BASIS`,
  `Legitimate Interest means the interest of our business in conducting and managing our business to enable us to give you the best service/product and the best and most secure experience. We make sure we consider and balance any potential impact on you (both positive and negative) and your rights before we process your personal data for our legitimate interests. We do not use your personal data for activities where our interests are overridden by the impact on you (unless we have your consent or are otherwise required or permitted to by law). You can obtain further information about how we assess our legitimate interests against any potential impact on you in respect of specific activities by contacting us.`,
  `Performance of Contract means processing your data where it is necessary for the performance of a contract to which you are a party or to take steps at your request before entering into such a contract.`,
  `Comply with a legal obligation means processing your personal data where it is necessary for compliance with a legal obligation that we are subject to.`,
  `THIRD PARTIES`,
  `External Third Parties`,
  `· Service providers acting as processors based in the UK who provide IT and system administration services.`,
  `· Professional advisers acting as processors or joint controllers including lawyers, bankers, auditors and insurers based in the UK who provide consultancy, banking, legal, insurance and accounting services.`,
  `YOUR LEGAL RIGHTS`,
  `You have the right to:`,
  `Request access to your personal data (commonly known as a "data subject access request"). This enables you to receive a copy of the personal data we hold about you and to check that we are lawfully processing it.`,
  `Request correction of the personal data that we hold about you. This enables you to have any incomplete or inaccurate data we hold about you corrected, though we may need to verify the accuracy of the new data you provide to us.`,
  `Request erasure of your personal data. This enables you to ask us to delete or remove personal data where there is no good reason for us continuing to process it. You also have the right to ask us to delete or remove your personal data where you have successfully exercised your right to object to processing (see below), where we may have processed your information unlawfully or where we are required to erase your personal data to comply with local law. Note, however, that we may not always be able to comply with your request of erasure for specific legal reasons which will be notified to you, if applicable, at the time of your request.`,
  `Object to processing of your personal data where we are relying on a legitimate interest (or those of a third party) and there is something about your particular situation which makes you want to object to processing on this ground as you feel it impacts on your fundamental rights and freedoms. You also have the right to object where we are processing your personal data for direct marketing purposes. In some cases, we may demonstrate that we have compelling legitimate grounds to process your information which override your rights and freedoms.`,
  `Request restriction of processing of your personal data. This enables you to ask us to suspend the processing of your personal data in the following scenarios:`,
  `· If you want us to establish the data's accuracy.`,
  `· Where our use of the data is unlawful but you do not want us to erase it.`,
  `· You have objected to our use of your data but we need to verify whether we have overriding legitimate grounds to use it. `,
  `Request the transfer of your personal data to you or to a third party. We will provide to you, or a third party you have chosen, your personal data in a structured, commonly used, machine-readable format. Note that this right only applies to automated information which you initially provided consent for us to use or where we used the information to perform a contract with you.`,
  `Withdraw consent at any time where we are relying on consent to process your personal data. However, this will not affect the lawfulness of any processing carried out before you withdraw your consent. If you withdraw your consent, we may not be able to provide certain products or services to you. We will advise you if this is the case at the time you withdraw your consent.`,
]


export default function PrivacyPolicy() {

  return (
    <main className={styles.privacy_page} >

      <h1>Website privacy policy (UK)</h1>

      <div className={styles.content} >
        {
          termsContent.map( text => <p>{text}</p> )
        }
      </div>

    </main>
  )
}
